org: dotportion
service: dotportion-landing-api
custom:
  prune:
    automatic: true
    number: 2
  domains:
    dev: api-dev.dotportion.com
    prod: api.dotportion.com
  customDomain:
    domainName: ${self:custom.domains.${self:provider.stage}}
    stage: ${self:provider.stage}
    createRoute53Record: false
    basePath: "landing"
    endpointType: "regional"

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ssm:GetParameter"
      Resource: "arn:aws:ssm:${self:provider.region}:${aws:accountId}:parameter/dotportion/${self:provider.stage}/*"

  # Environment variables will be available to all your functions
  # It's highly recommended to use a service like AWS Secrets Manager for production
  environment:
    MONGO_URI: ${ssm:/dotportion/${self:provider.stage}/mongo_uri}
    MDataBase: ${self:provider.stage}
    ZOHO_HOST: ${ssm:/dotportion/${self:provider.stage}/zoho_host}
    ZOHO_PORT: ${ssm:/dotportion/${self:provider.stage}/zoho_port}
    AUTH_MAIL: ${ssm:/dotportion/${self:provider.stage}/auth_mail}
    AUTH_PASSWORD: ${ssm:/dotportion/${self:provider.stage}/auth_password}
    BASE_URL: https://${self:custom.domains.${self:provider.stage}}

functions:
  # Handles adding a user to the waitlist
  waitlist:
    handler: create-waitlist.handler
    timeout: 30
    events:
      - http:
          path: /waitlist
          method: post
          cors: true

  # Handles subscribing a user to the newsletter
  subscribe:
    handler: subscribe-newsletter.handler
    timeout: 30
    events:
      - http:
          path: /subscribe
          method: post
          cors: true

  # # Handles unsubscribing a user from the newsletter
  unsubscribe:
    handler: unsubscrible-newsletter.handler
    timeout: 30
    events:
      - http:
          path: /unsubscribe
          method: get
          cors: true

plugins:
  - serverless-offline
  - serverless-prune-plugin
  - serverless-domain-manager

# This tells the packaging process to exclude the AWS SDK, which is already available in the Lambda environment.
package:
  individually: true
  exclude:
    - node_modules/aws-sdk/**
