export const ErrorTypes = {
  MISSING_PARAM: "MISSING_PARAM",
  WORKFLOW_NOT_FOUND: "WORKFLOW_NOT_FOUND",
  EXECUTION_FAILED: "EXECUTION_FAILED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  INVALID_INPUT: "INVALID_INPUT",
  PARAMETER_PROCESSING_FAILED: "PARAMETER_PROCESSING_FAILED",
};
